import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import api from "../api/client.js";
import { trackProjectClick } from "../api/analytics.js";

export const suppliedProjects = [
  { _id: "ali-brand", tag: "E-Commerce", title: "Ali.Ecom — Brand Growth System", mediaUrl: "/projects/ali-ecom-brand.jpeg", mediaType: "image", client: "Ali.Ecom", industry: "E-Commerce", description: "A conversion-led e-commerce growth identity built around traffic, orders, revenue and smarter campaign decisions.", objective: "Create a clear performance-focused brand presence for an e-commerce growth service.", strategy: "Used bold red visual language and four outcome pillars to communicate the growth offer at a glance.", metrics: [{ label: "Focus", value: "Growth" }, { label: "Channels", value: "E-Com" }, { label: "Goal", value: "Sales" }] },
  { _id: "uk-growth", tag: "Sales Growth", title: "Ali.Ecom — UK Store Performance", mediaUrl: "/projects/ecom-uk-growth.jpeg", mediaType: "image", client: "Ali.Ecom", industry: "E-Commerce", description: "Store performance snapshot showing a sharp uplift in traffic, sales and orders for an e-commerce campaign.", objective: "Scale qualified sessions while converting more store visits into paid orders.", strategy: "Optimised campaign structure and conversion-led traffic to turn store activity into measurable sales growth.", metrics: [{ label: "Sales", value: "£3,880" }, { label: "Orders", value: "71" }, { label: "Sessions", value: "2,776" }] },
  { _id: "us-growth", tag: "Revenue Scale", title: "Ali.Ecom — US Revenue Growth", mediaUrl: "/projects/ecom-us-growth.jpeg", mediaType: "image", client: "Ali.Ecom", industry: "E-Commerce", description: "A high-growth e-commerce result featuring increased sessions, order volume and revenue over the campaign period.", objective: "Build scalable revenue while protecting average order value.", strategy: "Focused media buying on purchase-ready audiences and scaled winning ad sets against live sales data.", metrics: [{ label: "Sales", value: "US$19K" }, { label: "Orders", value: "409" }, { label: "Sessions", value: "8,187" }] },
  { _id: "uae-growth", tag: "Revenue Growth", title: "Ali.Ecom — UAE Store Results", mediaUrl: "/projects/ecom-aed-growth.jpeg", mediaType: "image", client: "Ali.Ecom", industry: "E-Commerce", description: "A real-results dashboard showing sustained session, sales and order growth for an AED e-commerce store.", objective: "Increase sales volume and make the e-commerce offer more visible in a competitive market.", strategy: "Combined clear creative positioning with campaign optimisation around the products and audiences driving sales.", metrics: [{ label: "Sales", value: "AED 6,941" }, { label: "Orders", value: "67" }, { label: "Sessions", value: "1,292" }] },
  ...["01", "02", "03", "04", "05", "06", "07"].map((number, index) => ({ _id: `ecom-video-${number}`, tag: "Video Case Study", title: `Ali.Ecom — Campaign Reel ${number}`, mediaUrl: `/projects/ecom-reel-${number}.mp4`, mediaType: "video", client: "Ali.Ecom", industry: "E-Commerce", description: "A campaign-performance video reel documenting an Ali.Ecom e-commerce growth project.", objective: "Present the campaign results and creative direction in a concise video format.", strategy: "Used performance-led visual storytelling to highlight traffic, order and revenue outcomes.", metrics: [{ label: "Format", value: "Video" }, { label: "Campaign", value: `0${index + 1}` }, { label: "Focus", value: "Growth" }] })),
];

export default function Portfolio() {
  const [caseStudies, setCaseStudies] = useState(suppliedProjects);
  const [loading, setLoading] = useState(true);
  const [selectedProject, setSelectedProject] = useState(null);
  const [page, setPage] = useState(0);
  const perPage = 3;

  useEffect(() => { api.get("/case-studies").then((res) => { if (res.data?.length) setCaseStudies([...suppliedProjects, ...res.data]); }).catch(() => {}).finally(() => setLoading(false)); }, []);
  const pageCount = Math.ceil(caseStudies.length / perPage);
  const visibleProjects = useMemo(() => caseStudies.slice(page * perPage, page * perPage + perPage), [caseStudies, page]);
  const openProject = (project) => { trackProjectClick(project.title); setSelectedProject(project); };

  return <section id="portfolio"><div className="wrap"><div className="section-head"><span className="eyebrow">Portfolio</span><h2 className="display">Featured Campaigns</h2><p>Performance-led e-commerce campaigns, results dashboards and video case studies.</p></div>
    {loading ? <div className="loading-row">Loading case studies…</div> : <><AnimatePresence mode="wait"><motion.div className="case-grid" key={page} initial={{ opacity: 0, y: 16, rotateX: -3 }} animate={{ opacity: 1, y: 0, rotateX: 0 }} exit={{ opacity: 0, y: -12, rotateX: 3 }} transition={{ duration: 0.3 }}>{visibleProjects.map((c) => <motion.div className="case-card" key={c._id} whileHover={{ y: -8, rotateX: 2, rotateY: -2 }}><div className="case-media">{c.mediaType === "video" ? <video src={c.mediaUrl} muted preload="metadata" playsInline /> : <img src={c.mediaUrl || c.imageUrl} alt={c.title} />}<span className="case-tag">{c.tag}</span>{c.mediaType === "video" && <span className="video-badge">▶ Video</span>}</div><div className="case-body"><h3>{c.title}</h3><div className="case-metrics">{c.metrics?.slice(0, 3).map((m) => <div key={m.label}><span className="m-lbl">{m.label}</span><span className="m-val">{m.value}</span></div>)}</div><button type="button" className="case-link" onClick={() => openProject(c)}>View Case Study →</button></div></motion.div>)}</motion.div></AnimatePresence><div className="portfolio-pagination"><button className="btn btn-ghost" disabled={page === 0} onClick={() => setPage((current) => current - 1)}>← Previous</button><span>{page + 1} / {pageCount}</span><button className="btn btn-primary" disabled={page >= pageCount - 1} onClick={() => setPage((current) => current + 1)}>Next 3 Projects →</button></div></>}
    <AnimatePresence>{selectedProject && <motion.div className="project-modal" role="dialog" aria-modal="true" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelectedProject(null)}><motion.article className="project-detail" initial={{ opacity: 0, y: 30, rotateX: -7 }} animate={{ opacity: 1, y: 0, rotateX: 0 }} exit={{ opacity: 0, y: 15, rotateX: 5 }} onClick={(event) => event.stopPropagation()}><button className="project-close" type="button" onClick={() => setSelectedProject(null)} aria-label="Close case study">×</button>{selectedProject.mediaType === "video" ? <video src={selectedProject.mediaUrl} controls autoPlay playsInline /> : <img src={selectedProject.mediaUrl || selectedProject.imageUrl} alt={selectedProject.title} />}<span className="eyebrow">{selectedProject.tag}</span><h3>{selectedProject.title}</h3><p>{selectedProject.description}</p><div className="project-info"><div><b>Client</b><span>{selectedProject.client || "Portfolio Client"}</span></div><div><b>Industry</b><span>{selectedProject.industry || selectedProject.tag}</span></div></div><section><h4>Objective</h4><p>{selectedProject.objective || "Deliver measurable campaign growth."}</p></section><section><h4>Strategy</h4><p>{selectedProject.strategy || "Optimised campaign and creative strategy around business outcomes."}</p></section><section><h4>Results</h4><div className="case-metrics">{selectedProject.metrics?.map((m) => <div key={m.label}><span className="m-lbl">{m.label}</span><span className="m-val">{m.value}</span></div>)}</div></section></motion.article></motion.div>}</AnimatePresence>
  </div></section>;
}
